##########
# timeline-recipe
# Jekyll template to use TimelineJS
# https://github.com/evanwill/timeline-recipe
##########

##########
# URL VARIABLES
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://evanwill.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /timeline-recipe
# location of code, the full url to your github repository
source-code: https://github.com/evanwill/timeline-recipe

##########
# SITE SETTINGS
#
# title of site appears in header
title: Timeline Demo
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: a template for creating timeline exhibits
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Timeline-recipe is a template for creating timeline exhibits on GitHub Pages using a standalone version of TimelineJS"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: evanwill
# date project was created
date: 2020

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
